project:
  type: website
  output-dir: docs

website:
  title: "Data science thinking"
  site-url: https://datascience-thinking.github.io
  description: "Tiny changes"
  page-navigation: false
  
  page-footer:
    left: "This page is produced with [Quarto](https://quarto.org/)."
    right:
      - text: "License"
        href: LICENSE
  
  repo-url: https://github.com/datascience-thinking
  repo-actions: [edit, issue]
  
  sidebar:
#    logo: "img/logo.png"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 3
    border: true
    
    contents:
      - file: index.qmd
        text: "Welcome"
      - file: agenda.qmd
        text: "Agenda"
      - href: related.qmd
        text: "Resources"

format:
  html:
    theme: cosmo #yeti #cosmo #solar 
    toc: true
    css: styles.css

execute:
  freeze: auto