---
title: "Related work"
subtitle: "A collection of publications, software and initiatives that, in our view, are related to data science thinking"
---

## Core publications 

* [Good Data Science Practice: Moving Toward a Code of Practice for Drug Development](https://doi.org/10.1080/19466315.2022.2063172). Mark Baillie, Conor Moloney, Carsten Philipp Mueller, Jonas Dorn, Janice Branson & David Ohlssen. (2023). Statistics in Biopharmaceutical Research. https://doi.org/10.1080/19466315.2022.2063172   

* [The Role of Statistical Thinking in Biopharmaceutical Research](https://doi.org/10.1080/19466315.2023.2224259). Frank Bretz & Joel B. Greenhouse. (2023). Statistics in Biopharmaceutical Research 15:3, pages 458-467. https://doi.org/10.1080/19466315.2023.2224259

* [Effective Visual Communication for the Quantitative Scientist](https://doi.org/10.1002/psp4.12455). Marc Vandemeulebroecke, Mark Baillie, Alison Margolskee, Baldur Magnusson. CPT Pharmacometrics Syst. Pharmacol., 8: 705-719. https://doi.org/10.1002/psp4.12455


## Effective visual communication 

The home page for effective visual communication and good graphical principles for quantitative scientists can be found [here](https://graphicsprinciples.github.io). 

## Related works 

References and further reading material used to support the workshop. 

* [Cox (2017)](https://doi.org/10.1007/s10654-017-0288-1) Statistical Science: A Grammar for Research. European Journal of Epidemiology 32: 465–71.

* [Cummings et al. (2007)](http://cii.org.ar/epidemiology/Conceiving%20the%20Research%20Question.pdf) Conceiving The Research Question In: Hulley et al (editors) Designing clinical research.

* [International Council for Harmonisation (2019)](https://www.ema.europa.eu/en/documents/scientific-guideline/ich-e9-r1-addendum-estimands-and-sensitivity-analysis-clinical-trials-guideline-statistical-principles-clinical-trials-step-5_en.pdf) ICH E9(R1): Estimands and sensitivity analysis in clinical trials. 

* [Richardson et al. (1995)](https://doi.org/10.7326/ACPJC-1995-123-3-A12). The well-built clinical question: A key to evidence-based decisions. ACP Journal Club, 123, A12-13. 

* [Vance et al. (2022)](https://doi.org/10.1002/sta4.471) Asking great questions. Stat, 11(1), p.e471. 

* [Bouchrika (2023)](https://research.com/research/how-to-write-a-research-question). How to write a research question: Types, steps, and examples.  

* [Haynes (2006)](https://doi.org/10.1016/j.jclinepi.2006.06.006) Forming research questions. Journal of Clinical Epidemiology 59: 881–86.  

* [Mallows (1998)](https://doi.org/10.1080/00031305.1998.10480528) The Zeroth Problem. The American Statistician 52: 1–9.

* [Hernán, M.A., Hsu, J. and Healy, B., 2019](https://www.tandfonline.com/doi/full/10.1080/09332480.2019.1579578). A second chance to get causal inference right: a classification of data science tasks. Chance, 32(1), pp.42-49

* [Kenett, R.S. and Redman, T.C., 2019](https://onlinelibrary.wiley.com/doi/book/10.1002/9781119570790). The real work of data science: turning data into information, better decisions, and stronger organizations. John Wiley & Sons.

* [Shmueli, Galit](https://www.stat.berkeley.edu/~aldous/157/Papers/shmueli.pdf). "To explain or to predict?." (2010): 289-310.

* [Wild, Chris J, and Maxine Pfannkuch, 1999](https://iase-web.org/documents/intstatreview/99.Wild.Pfannkuch.pdf). "Statistical Thinking in Empirical Enquiry." International Statistical Review 67 (3): 223–48.

* [MacKay, R Jock, and R Wayne Oldford, 2000](https://projecteuclid.org/journals/statistical-science/volume-15/issue-3/Scientific-Method-Statistical-Method-and-the-Speed-of-Light/10.1214/ss/1009212817.full). "Scientific Method, Statistical Method and the Speed of Light." Statistical Science, 254–78.

